### ISSUE TITLE
Uses tracker-sparql-0.10

### ISSUE THREAD

**Issue by hadess** [media-explorer/media-explorer#139]
0.12 is the current one.

**Comment by ghost** [comment]
It's only our webremote applet that depends on tracker.
Could we (and by we I willing to do the job) rewrite that piece of code so we use tracker through grilo and get rid of that dependency ?
Plus we get asynchronous code for free by using grilo !

**Comment by ghost** [comment]
We now check for either version 7857bd56332d086c50c1c8b247760551fbcf9c39 I'm not sure it's worth re-writing this to use grilo at the moment as there is likely to be changes in how we store and access our content. Also we don't mind it being syncronous because it's all api called via ajax.

Awaiting testing from @dlespiau

**Comment by dlespiau** [comment]
works for me, we can now build with either tracker-0.10 or tracker-0.12
