### ISSUE TITLE
Background manager is playing up

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#144]
I thought I had fixed this but, on exit I think the background manager is emitting some signals on behalf of a disposed background which is causing a callback to try and remove them from a container.

**Comment by thos** [comment]
It looks like the background manager attempts to use a new background if the existing one is destroyed, which causes the "changed" signal to be emitted, which the application uses to unparent the old background and parent the new one. I don't think it's a good idea for the background manager to switch to a new background if the existing one has been destroyed, since it can't know the reason for it's destruction.

**Comment by thos** [comment]
I fixed this by removing the code that loads a new background if the existing one was destroyed.
