### ISSUE TITLE
Media explorer should be a UPnP media renderer

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#176]
For instance by using Rygel http://live.gnome.org/Rygel

**Comment by rossburton** [comment]
I've been leaning on Michael to test this (using the MPRIS bridge in Rygel) because we want it in Guacamayo.

Michael, can you give a brief summary of what works and what doesn't at the moment?

**Comment by ghost** [comment]
The main gap at the moment is http://specifications.freedesktop.org/mpris-spec/latest/Player_Node.html#Property:Metadata Otherwise at the moment there is a very large range of results when testing with different combinations, upnp<->mpris often loses a bit of functionality and mrpis<-> client depends on the client a lot of the time. If I use my phone as the upnp cp a different set of things do and don't work, but in all cases mex did play and provide basic control of the media (play/pause).

**Comment by ghost** [comment]
Bug scrub, is now a player but would be nice to have #234
