### ISSUE TITLE
Doesn't check for x-huge presence in Tumbler

### ISSUE THREAD

**Issue by guiodic** [media-explorer/media-explorer#21]
Mex seems unable to read/generate thumbnails from local files:

Mex-Message: Cannot generate thumbnail for file:///home/guido/Video/big%20bang%20theory/The.Big.Bang.Theory.4x04.La.Deviazione.Del.Troll.Virtuale.ITA.DLMux.XviD-NovaRip.avi: Unsupported thumbnail flavor requested
Mex-Message: Cannot generate thumbnail for file:///home/guido/Video/big%20bang%20theory/The.Big.Bang.Theory.4x02.L.Esaltazione.Dei.Vegetali.Cruciferi.ITA.DLMux.XviD-NovaRip.avi: Unsupported thumbnail flavor requested
Mex-Message: Cannot generate thumbnail for file:///home/guido/Scrivania/screenshot1.png: Unsupported thumbnail flavor requested

I installed tumbler 0.1.21 (according Mex documentation http://media-explorer.github.com/docs/dependencies.png)

**Comment by ghost** [comment]
I think you're having this warning because we depend on a specific version of tumbler :
https://github.com/rossburton/tumbler

This version allows to generate "huge" thumbnails that suit well the UI of media explorer. Otherwise you would end up with pixelated thumbnails (because stretched too much).

**Comment by guiodic** [comment]
thank you, I merged ross burton's tumbler with tumbler 0.1.21 from (x)ubuntu and it works fine.
I'll do a PPA for mex soon.

**Comment by dlespiau** [comment]
Note that Ross' work has been accepted upstream and will be in the next tumbler http://git.xfce.org/xfce/tumbler/commit/?id=88a5e9692fcc2f2b64c152f25a98721d631b2ad7

**Comment by guiodic** [comment]
good! Thank you

**Comment by rossburton** [comment]
Upstream haven't accepted _all_ of the patches.  This problem is because we ask for a "x-huge" flavour (512x512px) that normal tumbler doesn't support.

The fix would be to ping Tumbler at startup and see what flavours it supports.  If it supports x-huge ask for it, otherwise just use normal.

**Comment by guiodic** [comment]
I see the gstreamer backend was accepted, but I don't build it for my tumblailer version, but mex works good, then only x-huge is actually needed for Mex. Is it so?

**Comment by rossburton** [comment]
Yeah, you don't _need_ the gstreamer plugin, if you're happy with the ffmpeg plugin or you can rely on something else such as Nautilus doing the thumbnailing.

The historical reason for me writing the GStreamer plugin to tumbler was that MeeGo doesn't -- and can't -- ship a fully-featured ffmpeg due to legal issues.

**Comment by dlespiau** [comment]
We only have the internal thumbnailer and never use tumbler, closing this.
