### ISSUE TITLE
GNOME-DVB Plugin

### ISSUE THREAD

**Issue by semiot** [media-explorer/media-explorer#41]
Add the gnome-dvb-daemon plugin integration to Master that lies in the thomas/dvb-plugin branch. Provide very basic way for users to watch digital TV via MEX.

**Comment by dlespiau** [comment]
Seems ready to commit (with the 2 small remarks on the branch itself). Careful that the build stuff around the plugins has changed, it's all in plugins/Makefile.am now so you will have to change that. It allows make -j5 to compile/link all the plugins at the same time instead of having to wait in sequence.

**Comment by semiot** [comment]
What's the status of this? Will it be part of the next release?

**Comment by thos** [comment]
The branch has been merged into master.
