### ISSUE TITLE
Bugs-Mex build on ubuntu

### ISSUE THREAD

**Issue by sijisunny** [media-explorer/media-explorer#57]
jhbuild(clutter) is returning errors 
Error Log
CCLD cally-atkcomponent-example /usr/lib/i386-linux-gnu/libpangocairo-1.0.so: undefined reference to `cairo_ft_font_face_create_for_pattern' /usr/lib/i386-linux-gnu/libpangocairo-1.0.so: undefined reference to`cairo_ft_font_options_substitute' /usr/lib/i386-linux-gnu/libpangocairo-1.0.so: undefined reference to `cairo_ft_scaled_font_lock_face' /usr/lib/i386-linux-gnu/libpangocairo-1.0.so: undefined reference to`cairo_ft_scaled_font_unlock_face' collect2: ld returned 1 exit status

**Comment by dlespiau** [comment]
Hi,

you could:

1/ Use a ppa with the latest release (0.1.0, quite old but hopefully the ppa will be updated with the release later this week)
https://launchpad.net/~guido-iodice/+archive/meego

2/ Try https://live.gnome.org/GnomeShell/RemovingLaFiles

**Comment by ghost** [comment]
I've also added some more documentation on building it on Ubuntu on the wiki https://github.com/media-explorer/media-explorer/wiki/Installing (See Building from source > Ubuntu natty)

**Comment by dlespiau** [comment]
Hey, any progress there? media-explorer compiles on Ubuntu as there is a ppa for it. If you are not very familiar with build matter I'd suggest to use the ppa as its maintainer seems happy to maintain it and since we'll have _at least_, one release a month.

I think I'm just going to close the issue, but more help needed to build it (which can happen on the mailing list/irc channel (#mex on gimpnet)), is that ok with you?
