### ISSUE TITLE
Split MexColumn into MexColumnFrame + MexColumn

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#61]
In the current UI the MexColumn is a composed of an header + a set of children.
Since we added touch support to the UI, it is now possible to scroll the column by dragging one of the children, but the header must remain at a fixed position.

The problem is that, currently the children and the headers are all together in a scrollview, which makes difficult to fix the position the header of the column. We can still see a flickering effect on the header when moving the focus very fast from the header to the bottom of the column.

We need to split the MexColumn into 2 widgets, one containing the header and a scrollview (MexColumnFrame). And another containing all the children (MexColumn).

**Comment by Cwiiis** [comment]
I really don't think we need to split these widgets up, this can easily be done by just fixing MexColumn. Instead of hooking allocate to the adjustment value changing, stick with redraw and add a callback on the adjustment value notify that re-allocates the header (this is fine).

I'll push a patch on the weekend - please don't split these two up, I think Mex has enough classes :)

**Comment by ghost** [comment]
Arg !
I was thinking to do something like that... I just forgot that the adjustment can notify its value changing...

Looks like a bit dodgy though, are supposed to allocate outside the allocation cycle ?

**Comment by Cwiiis** [comment]
I'm sure people will tell you not to, but technically and
realistically it's fine and I've done it lots before. It's a lot more
optimal than causing everything to run its allocation again
(especially if the allocation cache gets missed for whatever reason).

On 24 June 2011 09:24, llandwerlin42
reply@reply.github.com
wrote:

**Comment by thos** [comment]
I think the problem could be avoided if the scrolling behaviour was internal to MexColum. The header and children could then be allocated separately and there would be no need to re-allocate the header.

**Comment by Cwiiis** [comment]
The scrolling is internal to MexColumn, but you have to allocate either the
header or the children in order to not break picking. Will push a patch
later.
On Jun 27, 2011 3:53 AM, "thos" <
reply@reply.github.com>
wrote:

**Comment by thos** [comment]
MexColumn implements scrollable and is placed in a MexScrollView by MexExplorer. My suggestion is for MexColumn not to implement MxScrollable, but instead use an MexScrollView internally and only use it for items in the column. This way the header actor would not have to be added to any scrollable actor.

**Comment by Cwiiis** [comment]
We did that before, but then you have the problem that MexColumn would no
longer be a container - there are hacks you can do to make it behave
somewhat like one, but they tend to end up breaking things. The fix for this
is pretty trivial, I'll push a patch once I get into the office (not your
office :))
On Jun 27, 2011 8:50 AM, "thos" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
Fixed in 0be392f1b1b53222f0b0

**Comment by ghost** [comment]
I'm reopening that one because even though we managed to workaround the header position issue, we now face a scrolling problem, with part of a tile being hided by the column header when the scrollview tries to ensure the tile is visible.

I pushed the https://github.com/media-explorer/media-explorer/tree/mex-column-view branch which splits the header/scrollview from the column of tiles, making things a bit simpler.

Thomas, you're probably the most qualified person to review that branch.

**Comment by thos** [comment]
I've added a few comments on the commit, but there is quite a bit of debugging and commented out code that needs removing to make it easier to review.

**Comment by Cwiiis** [comment]
I don't have time to look over this properly, but have you worked around the issue that splitting MexColumn up will mean that it no longer 'owns' its children? The last time we had them split, we had all sorts of issues with the proxies because the column wasn't the direct parent of its child (we had some work-arounds, but they were hacky and often lead to crashing/leaking).

I'd say that fixing the ensure-visible mechanism is a much easier problem than the one above, but if you've sorted that out then good stuff :)

**Comment by ghost** [comment]
The current code uses a ScrollView as container for the whole Column. With this branch the container becomes a ColumnView (which includes the header + ScrollView) and the Proxy is still working with the Column as it was before.

I might have missed something, but as far as I can tell there shouldn't be a problem around proxies/ClutterContainer.

The folding/unfolding of tiles was a much more tricky part to understand :)

**Comment by thos** [comment]
Just had a quick go with the branch, I noticed two regressions:
- Clicking the columns no longer focuses them
- The special styling for the search column is no longer applied

There are also some more issues with columns, but these also appear in master. It would be good if we could make sure they were fixable with the new classes:
- When returning to the home screen from some content, the column sometimes shows all the items expanded
- Clicking an opened item doesn't close it

**Comment by ghost** [comment]
Ok, I took care of the 2 regressions.

The first is fixed in 4925ca6f2334d098fbe7bdf9233324c3bcf520db.
The second is fixed in e1ecd5f33b8a575acfa3a231411925b7041b64b7.

I also fixed the fourth in 60cd9627308507b7ddaf9e0fe5b8f3b1cfac85fe.
