### ISSUE TITLE
Nearly fullscreen mode

### ISSUE THREAD

**Issue by hadess** [media-explorer/media-explorer#79]
By default, on the GNOME target, mex should start as a mostly fullscreen application:
- no titlebar, window takes the whole screen minus the panel
- GNOME shell panel should still be visible
- removes the need for a clock
- removes the need for a close button (application menu -> close, or overview -> (X))

**Comment by hadess** [comment]
Would close #74, #75 and #76

**Comment by semiot** [comment]
Hi, 

While I understand the value of this in order not to replicate the clock, I have a few questions about the rest. 
1. Wouldn't doing this mean that you'd also see the GNOME shell panel when you play a video or view a photo? This would be a bit distracting. 
2. As an alternative, were you imagining that once a piece of media was being played that the shell panel disappears? Is having the shell panel visible or not something that can be easily manipulated by an app? Is it a pure show/hide option or can this be animated? 
3. The close button:  Don't all standard GNOME windows have an X? So in effect we would still have a close button, but it would be part of the GNOME chrome by doing it this way?

Because MEX uses the top and bottom of the screen in ways that are different to GNOME's model of the shell panel and notifications, we may not want to introduce mixed metaphors...

**Comment by hadess** [comment]
> 1. Wouldn't doing this mean that you'd also see the GNOME shell panel when you play a video or view a photo? This would be a bit distracting.

No. You can go from maximised without a titlebar to fullscreen easily. And you'd do this when you're _actually_ playing a film.

> 1. As an alternative, were you imagining that once a piece of media was being played that the shell panel disappears? Is having the shell panel visible or not something that can be easily manipulated by an app? Is it a pure show/hide option or can this be animated?

It's 100% the app being either maximised or being fullscreen.

> 1. The close button: Don't all standard GNOME windows have an X? So in effect we would still have a close button, but it would be part of the GNOME chrome by doing it this way?

If it doesn't have a titlebar, it wouldn't have a close button in its titlebar. It would get a close button in the overview because all windows do (even the ones without a titlebar).

> Because MEX uses the top and bottom of the screen in ways that are different to GNOME's model of the shell panel and notifications, we may not want to introduce mixed metaphors...

As discussed in other bugs, we don't want MEX to be doing its own notifications when running under GNOME. GNOME is the environment, it already has code to handle USB sticks being plugged in, integrated with the rest of the desktop, we don't want to replicate the code or the behaviour within MEX.

I think that the implementation is probably 10 to 15 minutes' worth of work for somebody who knows the codebase. I think it would be best for somebody to implement it "quickly" as a proof of concept.

**Comment by hadess** [comment]
I'll add this to the discussion as well, while researching https://live.gnome.org/Design/Proposals/FullscreenControls, I finally noticed that the "panel" on iOS is only visible when the fullscreen controls are visible, and hidden when the controls are hidden.

**Comment by semiot** [comment]
As mentioned in #82, I've added the mockups to the GNOME wiki page hadess created a few days ago to explore this:
https://live.gnome.org/Design/Proposals/FullscreenControls

**Comment by semiot** [comment]
Consolidating under #92: Mouse Interaction Model - will look at how we interact with desktop environments as part of this work.
